"""<>"""
class MongoConnection:
    """<>"""
    MONGODB_USER = 'MONGODB_USER'
    MONGODB_PASSWORD = 'MONGODB_PASSWORD'
    MONGODB_DATABASE = 'MONGODB_DATABASE'
    MONGODB_COLLECTION = 'MONGODB_COLLECTION'
